### ISSUE TITLE
Can grouping property of Self-Attention extend to Cross-Attention?

### ISSUE THREAD

**Issue by ByungJu-Woo** [NVlabs/FAN#25]
Hi, thank you for great work !

I have quention, if groping property of self attention can extend to cross-attention?
In perspective of information bottleneck, I wonder if Query can be grouping and noise filtering by Key (as temporary cluster center features), although Query and Key are from different input.

**Comment by zhoudaquan** [comment]
> Hi, thank you for great work !
> 
> I have quention, if groping property of self attention can extend to cross-attention? In perspective of information bottleneck, I wonder if Query can be grouping and noise filtering by Key (as temporary cluster center features), although Query and Key are from different input.

Hi ByungJu,

Thanks for the interesting discussion. I have not tried this myself but I do think it has the potential to be applied on the cross-attention module also. One potential benefit could be a better alignment between the text-visual features. Unfortunately, I am currently buried in some other projects and I cannot try it myself... If you want any other discussions or any extra experimental observations, you are more than welcome for a further discussion.

**Comment by ByungJu-Woo** [comment]
Thank you for answering !!

**Comment by zhoudaquan** [comment]
> Hi, thank you for great work !
> 
> I have quention, if groping property of self attention can extend to cross-attention? In perspective of information bottleneck, I wonder if Query can be grouping and noise filtering by Key (as temporary cluster center features), although Query and Key are from different input.

I think it is possible to happen since the grouping is done within the same data modality... But some experiments & visualizations are needed to verify the point you raised..
