### ISSUE TITLE
When will pre-trained models be released? 

### ISSUE THREAD

**Issue by Ga-Lee** [NVlabs/FAN#4]
Thank you for your excellent job! 
I want to be know the  rough time about when the pretrained models will be released.  : )

**Comment by zhoudaquan** [comment]
Hi,

Thanks for the interest. It depends on the approval time. We will release all checkpoints once approved. However, it is hard for me to estimate the time.

DQ

**Comment by Ga-Lee** [comment]
> Hi,
> 
> Thanks for the interest. It depends on the approval time. We will release all checkpoints once approved. However, it is hard for me to estimate the time.
> 
> DQ
