### ISSUE TITLE
Can't  download  the "Model"

### ISSUE THREAD

**Issue by chumingqian** [NVlabs/FAN#6]
Hi, authors:
         It seems  to be  can not  download  the  "Model"  from  the  link , currently.

**Comment by zhoudaquan** [comment]
> Hi, authors: It seems to be can not download the "Model" from the link , currently.

Hi,

Thanks for your interest. The models need to be checked by the corresponding person in the company before the release. We will try to make it as fast as possible.

Best regards,
DQ

**Comment by hpeiyan** [comment]
> 

您好，预训练模型有计划发布吗？大概什么时候呢？感谢解答

**Comment by zhoudaquan** [comment]
Hi,

The model checkpoint release has been approved by the company and we have released the pre-trained weights for the classification tasks. Please try with the model download link.

Thank you for your interests.

Best regards,
DQ

**Comment by pdejorge** [comment]
Any news for the segmentation and detection models? I'm particularly interested in the segmentation model for Cityscapes.

Regards,
Pau
