### ISSUE TITLE
The metric mCE may be calculated without jpeg_compression

### ISSUE THREAD

**Issue by wwd29** [NVlabs/FAN#7]
Some letters is uppercase in:
https://github.com/NVlabs/FAN/blob/e895863b49a839e6fe08f55dabea9bbcaf2ba341/utils/mce_utils.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L61
But lowercase in:
https://github.com/NVlabs/FAN/blob/e895863b49a839e6fe08f55dabea9bbcaf2ba341/validate_ood.py#L314
This may casue you missed the CE of jpeg compression.
https://github.com/NVlabs/FAN/blob/e895863b49a839e6fe08f55dabea9bbcaf2ba341/validate_ood.py#L336-L339
Then the results in your paper maybe need to correct.

**Comment by zhoudaquan** [comment]
> Some letters is uppercase in:
> 
> https://github.com/NVlabs/FAN/blob/e895863b49a839e6fe08f55dabea9bbcaf2ba341/utils/mce_utils.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L61
> 
> 
> But lowercase in:
> https://github.com/NVlabs/FAN/blob/e895863b49a839e6fe08f55dabea9bbcaf2ba341/validate_ood.py#L314
> 
> 
> This may casue you missed the CE of jpeg compression.
> https://github.com/NVlabs/FAN/blob/e895863b49a839e6fe08f55dabea9bbcaf2ba341/validate_ood.py#L336-L339
> 
> 
> Then the results in your paper maybe need to correct.

Hi,

Thanks for pointing out this typo. The results of mCE in Table 11 are calculated based on the excel sheets from https://docs.google.com/spreadsheets/d/1RwqofJPHhtdRPG-dDO7wPp-aGn-AmwmU5-rpvTzrMHw/edit#gid=0. We translate it into python scripts during code cleaning. Thus, the mCE results are correct in the paper. However, still, thank you so much for pointing out this typo!

Best regards,
Zhou Daquan
